import React, {useEffect, useState} from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const emptyWatch = {brand:'',model:'',reference:'',movement_type:'desconocido',diameter:'',approximate_year:'',condition:'usado',estimated_min_price:'',estimated_avg_price:'',estimated_max_price:'',recommended_buy_price:'',seen_price:'',resale_margin:'',counterfeit_risk:'medio',price_reliability:'media',identification_notes:'',prebuy_checklist:'',price_sources:'',location:'otro',quick_notes:'',status:'investigado'};
const api = (url, opts={}) => fetch(url, {credentials:'include', headers: opts.body instanceof FormData ? {} : {'Content-Type':'application/json'}, ...opts});
const money = v => v === null || v === undefined || v === '' ? '—' : new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(v);

function Login({onLogin}){const [username,setU]=useState('admin'),[password,setP]=useState(''),[err,setErr]=useState(''); async function submit(e){e.preventDefault(); const r=await api('/api/login',{method:'POST',body:JSON.stringify({username,password})}); if(r.ok) onLogin(); else setErr('Credenciales incorrectas');} return <main className="login"><section><h1>RastroWatch</h1><p>Escanea, registra y aprende el valor real de relojes de segunda mano.</p><form onSubmit={submit}><input value={username} onChange={e=>setU(e.target.value)} placeholder="Usuario"/><input type="password" value={password} onChange={e=>setP(e.target.value)} placeholder="Contraseña"/><button>Entrar</button>{err&&<b>{err}</b>}</form></section></main>}
function Card({w,onOpen}){return <article className="card" onClick={()=>onOpen(w)}><img src={w.images?.[0]?.url||'/placeholder.svg'} /><div><span className={`pill ${w.counterfeit_risk}`}>Riesgo {w.counterfeit_risk}</span><h3>{w.brand||'Marca pendiente'} {w.model}</h3><p>{w.reference||w.quick_notes||'Sin referencia'}</p><div className="split"><strong>{money(w.recommended_buy_price||w.seen_price)}</strong><em>{w.opportunity}</em></div></div></article>}
function WatchForm({current,onSaved}){const [w,setW]=useState(current||emptyWatch),[file,setFile]=useState(null); useEffect(()=>setW(current||emptyWatch),[current]); const set=(k,v)=>setW({...w,[k]:v}); async function save(e){e.preventDefault(); const payload=Object.fromEntries(Object.entries(w).map(([k,v])=>[k,v===''?null:v])); const r=await api(`/api/watches${w.id?`/${w.id}`:''}`,{method:w.id?'PUT':'POST',body:JSON.stringify(payload)}); const saved=await r.json(); if(file){const fd=new FormData(); fd.append('file',file); await api(`/api/watches/${saved.id}/images`,{method:'POST',body:fd});} onSaved();} return <form className="panel formgrid" onSubmit={save}><h2>{w.id?'Editar reloj':'Nuevo reloj'}</h2>{['brand','model','reference'].map(k=><input key={k} value={w[k]||''} onChange={e=>set(k,e.target.value)} placeholder={{brand:'Marca',model:'Modelo',reference:'Referencia'}[k]}/>) }<select value={w.movement_type||'desconocido'} onChange={e=>set('movement_type',e.target.value)}>{['cuarzo','automático','mecánico','solar','desconocido'].map(x=><option>{x}</option>)}</select><input type="number" step="0.1" value={w.diameter||''} onChange={e=>set('diameter',e.target.value)} placeholder="Diámetro mm"/><input type="number" value={w.approximate_year||''} onChange={e=>set('approximate_year',e.target.value)} placeholder="Año aproximado"/><select value={w.condition||'usado'} onChange={e=>set('condition',e.target.value)}>{['malo','usado','bueno','excelente','sin probar'].map(x=><option>{x}</option>)}</select>{['estimated_min_price','estimated_avg_price','estimated_max_price','recommended_buy_price','seen_price'].map(k=><input type="number" step="0.01" key={k} value={w[k]||''} onChange={e=>set(k,e.target.value)} placeholder={k.replaceAll('_',' ')}/>) }<select value={w.counterfeit_risk||'medio'} onChange={e=>set('counterfeit_risk',e.target.value)}>{['bajo','medio','alto'].map(x=><option>{x}</option>)}</select><select value={w.price_reliability||'media'} onChange={e=>set('price_reliability',e.target.value)}>{['baja','media','alta'].map(x=><option>{x}</option>)}</select><textarea value={w.identification_notes||''} onChange={e=>set('identification_notes',e.target.value)} placeholder="Notas de identificación"/><textarea value={w.prebuy_checklist||''} onChange={e=>set('prebuy_checklist',e.target.value)} placeholder="Qué revisar antes de comprar"/><textarea value={w.price_sources||''} onChange={e=>set('price_sources',e.target.value)} placeholder="Fuentes de precio"/><input type="file" accept="image/*" onChange={e=>setFile(e.target.files[0])}/><button>＋ Guardar</button></form>}
function QuickSeen({onSaved}){const [file,setFile]=useState(null); async function save(e){e.preventDefault(); const fd=new FormData(e.currentTarget); if(file)fd.set('file',file); await api('/api/quick-seen',{method:'POST',body:fd}); e.currentTarget.reset(); setFile(null); onSaved();} return <form className="panel quick" onSubmit={save}><h2>↥ Reloj visto</h2><input name="brand" placeholder="Marca si se conoce"/><input name="model" placeholder="Modelo si se conoce"/><input name="seen_price" type="number" step="0.01" placeholder="Precio visto"/><select name="location">{['rastrillo','Wallapop','tienda','particular','otro'].map(x=><option>{x}</option>)}</select><textarea name="quick_notes" placeholder="Notas rápidas"/><input type="file" accept="image/*" onChange={e=>setFile(e.target.files[0])}/><button>Guardar como pendiente de investigar</button></form>}
function Detail({w,onClose,onEdit}){if(!w)return null;return <div className="modal"><section className="detail"><button className="ghost" onClick={onClose}>Cerrar</button><div className="photos">{w.images?.map(i=><img src={i.url}/> )}</div><h2>{w.brand} {w.model}</h2><p className="alert">⚠ {w.valuation_warning||'Sin alertas fuertes registradas'}</p><div className="stats"><b>Máximo recomendado</b><span>{money(w.recommended_buy_price||w.estimated_max_price)}</span><b>Margen aprox.</b><span>{money(w.resale_margin)}</span><b>Recomendación</b><span>{w.recommendation}</span></div><h3>Datos técnicos</h3><p>{w.reference} · {w.movement_type} · {w.diameter||'—'} mm · {w.approximate_year||'—'} · estado {w.condition}</p><h3>Valoración</h3><p>Oportunidad {w.opportunity}. Precio visto {money(w.seen_price)}. Rango estimado {money(w.estimated_min_price)} - {money(w.estimated_max_price)}.</p><h3>Señales y aprendizaje</h3><p>{w.prebuy_checklist||'Añade señales de alerta.'}</p><p>{w.identification_notes||'Añade notas para identificarlo.'}</p><button onClick={()=>onEdit(w)}>Editar</button></section></div>}
function App(){const [auth,setAuth]=useState(false),[watches,setWatches]=useState([]),[q,setQ]=useState(''),[selected,setSelected]=useState(null),[editing,setEditing]=useState(null); async function load(){const r=await api('/api/watches?q='+encodeURIComponent(q)); if(r.status===401){setAuth(false);return} setWatches(await r.json()); setAuth(true)} useEffect(()=>{api('/api/me').then(r=>r.ok?setAuth(true):setAuth(false))},[]); useEffect(()=>{if(auth)load()},[auth,q]); if(!auth)return <Login onLogin={()=>setAuth(true)}/>; return <><header><div><h1>RastroWatch</h1><p>Escanea, registra y aprende el valor real de relojes de segunda mano.</p></div><button className="ghost" onClick={()=>api('/api/logout',{method:'POST'}).then(()=>setAuth(false))}>⎋ Salir</button></header><main className="layout"><section className="left"><div className="search"><span>🔎</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar marca, modelo, referencia o notas"/></div><div className="cards">{watches.map(w=><Card key={w.id} w={w} onOpen={setSelected}/>)}</div></section><aside><QuickSeen onSaved={load}/><WatchForm current={editing} onSaved={()=>{setEditing(null);load()}}/></aside></main><Detail w={selected} onClose={()=>setSelected(null)} onEdit={(w)=>{setEditing(w);setSelected(null)}}/></>}
createRoot(document.getElementById('root')).render(<App/>);
